package eventSystem;

public enum EventType {
    INSERT_HERSTELLER,
    INSERT_KUCHEN,
    DISPLAY_HERSTELLER,
    DISPLAY_KUCHEN,
    DISPLAY_ALLERGENE,
    DELETE_HERSTELLER,
    REMOVE_KUCHEN,
    UPDATE_INSPECTION_DATE,
    SAVE_JOS,
    LOAD_JOS,
    SAVE_JBP,
    LOAD_JBP
}
